name: Deploy
on:
  push:
    branches:
    - main

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy static content to public directory
      run: |
        sh prepare.sh
        cp public/index.html public/404.html
    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        CLEAN: true
